### ISSUE TITLE
Design Menu: Implement routes to different pages

### ISSUE THREAD

**Issue by limesoda314** [limesoda314/Data-Science-Academy-Website#13]
Add hover over, get rid of link underline, and add links

**Comment by ivanneto02** [comment]
I am using svelte-routing to create the routes between different pages. The Link component will be used to move between pages.

**Comment by ivanneto02** [comment]
At this point I've added svelte-routing functionality.

`src/routes/` contains each of the pages we are using.

To add pages, you add a `Page.svelte` file in `src/routes/`, and add a `<Route>` to `src/App.svelte` with the route. Further, you can add another item to the navigation bar in `src/Components/Navigation.svelte`
